version: '1'

networks:
    internal:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
          - "80:80"
        volumes:
          - ./www:/var/www
          - ./config/nginx:/etc/nginx/conf.d
          - ./logs:/var/log/nginx/
        depends_on:
          - php
          - mysql
        networks:
          - internal
    php:
        build:
          context: ./config/php
          dockerfile: Dockerfile
        container_name: php
        volumes:
          - ./www:/var/www
          - ./config/php/php.ini:/usr/local/etc/php/php.ini
        ports:
          - "9001:9000"
        networks:
          - internal
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0 --init-file /data/application/init.sql
        ports:
          - "3306:3306"
        volumes:
          - ./mysql:/var/lib/mysql
          - ./init.sql:/data/application/init.sql
        environment:
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: task
          MYSQL_PASSWORD: secret
        networks:
         - internal
